name: conda_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - absl-py
  - astor
  - cached-property
  - certifi
  - cycler
  - fonttools
  - gast
  - google-pasta
  - grpcio
  - h5py
  - importlib-metadata
  - Keras-Applications
  - Keras-Preprocessing
  - kiwisolver
  - Markdown
  - matplotlib
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy
  - opt-einsum
  - packaging
  - Pillow
  - pip
  - protobuf
  - pyparsing
  - python-dateutil
  - scipy
  - setuptools
  - six
  - tensorboard
  - tensorflow
  - tensorflow-estimator
  - termcolor
  - typing-extensions
  - webencodings
  - Werkzeug
  - wheel
  - wrapt
  - zipp
  - pip
  - pip:
    - opencv-python
