apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-mongo-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: files-mongo
  template:
    metadata:
      labels:
        app: files-mongo
    spec:
      containers:
        - name: files-mongo
          image: mongo

---
apiVersion: v1
kind: Service
metadata: 
  name: files-mongo-srv
spec:
  selector:
    app: files-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017