name: tests-model

on: 
  pull_request:
    paths:
      - 'model-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd model-service && npm install && npm run test:ci
