name: tests-projects

on: 
  pull_request:
    paths:
      - 'projects-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd projects-service && npm install && npm run test:ci
